site_name: AALibrary

theme:
  name: material
  logo: assets/NOAA-color-logo-no-text-print.png
  favicon: assets/noaa_favicon.png
  features:
    - search.suggest
    - search.highlight
    - content.code.copy
  icon:
    repo: fontawesome/brands/git-alt

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details

nav:
  - "Home": index.md
  - "Getting Started":
    - "Installation": getting-started/installation.md
    - "Permissions": getting-started/permissions.md
    - "Testing": getting-started/testing.md
  - "Usage":
    - "Downloads": usage/downloads.md
    - "Conversions": usage/conversions.md
    - "Uploads": usage/uploads.md
  - "Documentation":
    - "AALibrary": documentation/aalibrary.md
    - "Utils": documentation/utils.md
    - "RawFile": documentation/raw_file.md
    - "GCP Overview": documentation/gcp_overview.md
  - "Troubleshooting": troubleshooting/troubleshooting.md
  - "About":
    - "License": about/license.md
    - "Notice": about/notice.md
    - "Disclaimer": about/disclaimer.md

plugins:
- search:
    # This separator includes the `.` character to separate words for searching. 
    separator: '[\s\-\.]+'
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          show_source: false
          group_by_category: true
          summary: true
- git-revision-date-localized
